coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 100%

comment:
  layout: "reach,diff,flags,files"

ignore:
  - "spec/**"
  - "config/**"
  - "db/**"
  - "vendor/**"

fixes:
  - "/home/runner/work/erp_plus/erp_plus/::"
