fixes:
  - "::"

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 100%

comment:
  layout: "reach,diff,flags,files"
  behavior: default

ignore:
  - "spec/**"
  - "config/**"
  - "db/**"
  - "vendor/**"
  - "bin/**"

component_management:
  individual_components:
    - component_id: app
      name: App
      paths:
        - app/

    - component_id: erp_accounts
      name: ERP Accounts
      paths:
        - engines/erp_accounts/

    - component_id: erp_core
      name: ERP Core
      paths:
        - engines/erp_core/

    - component_id: erp_users
      name: ERP Users
      paths:
        - engines/erp_users/

    - component_id: erp_workers
      name: ERP Workers
      paths:
        - engines/erp_workers/
