coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 100%

comment:
  layout: "reach,diff,flags,files"
  behavior: default

ignore:
  - "spec/**"
  - "config/**"
  - "db/**"
  - "vendor/**"
  - "bin/**"

fixes:
  - "::"

flags:
  app:
    paths:
      - "app/"
  erp_accounts:
    paths:
      - "engines/erp_accounts/app/"
  erp_core:
    paths:
      - "engines/erp_core/app/"
  erp_users:
    paths:
      - "engines/erp_users/app/"
  erp_workers:
    paths:
      - "engines/erp_workers/app/"
