# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# ============================================
# RuboCop Config para Rails 8 + ViewComponent
# Basado en Omakase + mejoras modernas
# ============================================

# ============================================
# RUBOCOP CONFIG PARA RAILS 8 + ENGINES
# ============================================

# Ignora configuraciones de RuboCop dentro de mini_mime
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

# ============================================
# ARCHIVOS GENERALES
# ============================================
AllCops:
  UseCache: true
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "engines/**/node_modules/**/*"
    - "engines/**/tmp/**/*"
    - "engines/**/vendor/**/*"

  DisplayStyleGuide: true

# ============================================
# VIEW COMPONENTS
# ============================================

Metrics/ClassLength:
  Exclude:
    - "app/components/**/*"

Metrics/BlockLength:
  Exclude:
    - "app/components/**/*.html.slim"
    - "app/views/**/*.html.slim"

Layout/LineLength:
  Max: 120

# ============================================
# RAILS MODERNOS (8, Hotwire, Solid, etc.)
# ============================================

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/EnumHash:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

# ============================================
# RUBY MODERNO
# ============================================

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 50

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# ============================================
# RSpec
# ============================================

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/EmptyExampleGroup:
  Enabled: false

# ============================================
# FACTORY BOT
# ============================================

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false
