# =====================================================
# RUBOCOP CONFIG PARA RAILS 8 + ENGINES + FULL STACK
# Carlos — versión optimizada
# =====================================================

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance

# =====================================================
# SETTINGS GENERALES
# =====================================================

AllCops:
  UseCache: true
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  DisplayStyleGuide: true

  Exclude:
    # Infraestructura estándar
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"

    # Rails DB
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/**/*"

    # Engines: infraestructura que NO debe ser analizada
    - "engines/**/node_modules/**/*"
    - "engines/**/vendor/**/*"
    - "engines/**/tmp/**/*"
    - "engines/**/db/migrate/**/*"

    # Coverage, almacenamiento, cachés
    - "coverage/**/*"
    - "storage/**/*"

# =====================================================
# STYLE / LAYOUT
# =====================================================

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "app/javascript/controllers/**/*"

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "app/components/**/*"

Metrics/BlockLength:
  Exclude:
    - "app/views/**/*.html.*"
    - "app/components/**/*.html.*"
    - "spec/**/*"
    - "test/**/*"

Metrics/AbcSize:
  Max: 50

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# =====================================================
# RAILS — Config para Rails 8 moderno
# =====================================================

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/EnumHash:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

# =====================================================
# RSpec — configuración para proyectos grandes
# =====================================================

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/AnyInstance:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

# =====================================================
# FactoryBot — limpio y moderno
# =====================================================

FactoryBot:
  Enabled: true

FactoryBot/AttributeDefinedStatically:
  Enabled: true

FactoryBot/FactoryClassName:
  Enabled: true

# =====================================================
# PERFORMANCE COP (Opcional pero recomendado)
# =====================================================

Performance:
  Enabled: true
