# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
# ============================================
# RuboCop Config para Rails 8 + ViewComponent
# Basado en Omakase + mejoras modernas
# ============================================

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false

  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "engines/**/node_modules/**/*"
    - "engines/**/tmp/**/*"

  DisplayStyleGuide: true

# ============================================
# SLIM
# ============================================
Slim/Literal:
  Enabled: true

Slim/Interpolation:
  Enabled: true

Slim/ControlStatementSpacing:
  Enabled: true

# ============================================
# VIEW COMPONENTS
# ============================================

# Permite inicializadores con keyword args y opciones flexibles
Style/OptionalBooleanParameter:
  Enabled: false

# Componentes suelen tener muchos métodos pequeños
Metrics/ClassLength:
  Exclude:
    - "app/components/**/*"

# Plantillas Slim no deben ser penalizadas por longitud
Metrics/BlockLength:
  Exclude:
    - "app/components/**/*.html.slim"
    - "app/views/**/*.html.slim"

# ============================================
# RAILS
# ============================================

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/Blank:
  Enabled: true

# Para Rails 8 + SolidQueue + ActiveJob modernos
Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/EnumHash:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

# ============================================
# ESCRITURA MODERNA RUBY
# ============================================

# Permite métodos más largos cuando son componentes o helpers
Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 50

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Evita advertencias innecesarias en servicios y componentes
Style/ClassAndModuleChildren:
  Enabled: false

# Permite _ cuando es explícitamente útil
Naming/MethodParameterName:
  Enabled: false

# ============================================
# TESTS (RSpec)
# ============================================

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

# No queremos molestar por describe vacíos o temporales
RSpec/EmptyExampleGroup:
  Enabled: false

# ============================================
# FACTORIES
# ============================================
FactoryBot/ConsistentParenthesesStyle:
  Enabled: false
